### ISSUE TITLE
Keycloak: style login page on dev server

### ISSUE THREAD

**Issue by cklamann** [ccmbioinfo/osmp#105]

**Comment by hannahle** [comment]
Changes have been made on the [site](https://ssmp.ccmdev.ca/).

For future reference, this was done by using `docker cp` to copy `keycloak/theme/ssmp/.` to `/opt/jboss/keycloak/themes/ssmp`. Then, we'd have to manually log into our Keycloak's admin console and select `ssmp` as theme option from the dropdown.
