### ISSUE TITLE
React: csv export should not contain html or javascript objects

### ISSUE THREAD

**Issue by cklamann** [ccmbioinfo/osmp#125]
Currently `Cell` and other display components are included in the csv export. We should export only the data from the results.

**Comment by Sayantan-s** [comment]
Hey @cklamann, can you assign this to me? I can try & fix this.

**Comment by cklamann** [comment]
> Hey @cklamann, can you assign this to me? I can try & fix this.

Sorry, we can only accept contributions from organization members at this time. Thank you for your interest in the project.
