### ISSUE TITLE
React: show column info on hover

### ISSUE THREAD

**Issue by cklamann** [ccmbioinfo/osmp#126]
Each table column header should display metadata about the column's contents on hover. The metadata may change depending on the results, so the component should use a accessor function that takes the full results set as an argument (for now)

**Comment by Emiliano-Russo** [comment]
I would like to help, can you assign it to me?

**Comment by cklamann** [comment]
> I would like to help, can you assign it to me?

Sorry, we can only accept contributions from organization members at this time. Thank you for your interest in the project.
