### ISSUE TITLE
React: display one row per variant and expand when clicking on Case Details

### ISSUE THREAD

**Issue by hannahle** [ccmbioinfo/osmp#179]
- [x] Standardize the display for **Zygosity** column. Currently, we have mixed texts (such as "het", "Het", "Heterozygous", "heterozygous", etc.) coming from different sources. We should have a check that if the text contains "het" or "hom", display it as "Heterozygous" and "Homozygous" on the table, respectively. For other data that doesn't contain "het" or "hom", leave it as is. This can be accomplished using the `accessor` property in the column configuration of `react-table`. `Accessor` basically allows us to control what texts are being displayed, without changing the value on the backend directly (see more detailed documentation [here](https://react-table.tanstack.com/docs/api/useTable)). 

- [x] Add two columns to **Variant Details** group - **Heterozygous Count** and **Homozygous Count**. Each column represents how many heterozygous traits there are for a given variant. 

- [x] Currently, there are multiple patient cases for a single variant. When only **Variant Details** and **Variant** column groups are expanded, the table contains a list of repetitive rows of the same information. This makes the table look bulky. We only want to display one row for variant when **Case Details** are collapsed
 
- [x] Add alternating colors for the rows.

**Comment by jennyziyi-xu** [comment]
For the third task, should it say "We only want to display one row for variant when Case Details are collapsed"?

**Comment by hannahle** [comment]
> For the third task, should it say "We only want to display one row for variant when Case Details are collapsed"?

Yes, that's what I meant. Thanks for pointing out!

**Comment by jennyziyi-xu** [comment]
For standardizing the zygosity column, I wonder if it would be better to use the column option `Cell` instead of `accessor`.  I think `accessor` is for specifying which field to access in the row, whereas `Cell` is for displaying the value in the table cell. 

The column `sex` uses `Cell` to format the displayed value: [Table.tsx](https://github.com/ccmbioinfo/osmp/blob/0ee84e47ba3d0db1ef264a2cfbe4b726de70ae6c/react/src/components/Table/Table.tsx#L267).

**Comment by hannahle** [comment]
> For standardizing the zygosity column, I wonder if it would be better to use the column option `Cell` instead of `accessor`. I think `accessor` is for specifying which field to access in the row, whereas `Cell` is for displaying the value in the table cell.
> 
> The column `sex` uses `Cell` to format the displayed value: [Table.tsx](https://github.com/ccmbioinfo/osmp/blob/0ee84e47ba3d0db1ef264a2cfbe4b726de70ae6c/react/src/components/Table/Table.tsx#L267).

That's a good point. Can you double check if we can still **filter** data if we display the 'Heterozygous' / 'Homozygous' values in Cell instead of Accessor? If I recall correctly, for the filter function of `react-table` to work, the library looks at the text in `Accessor`. So if the user clicks on "Heterozygous" as a filter option, but `react-table` looks at accessor for that exact value instead of Cell, we might miss out on those rows.

**Comment by jennyziyi-xu** [comment]
You are right. We can't filter data properly if we use `Cell` column option. Yes, the library looks at the text returned by `Accessor` in order to filter the rows.

**Comment by jennyziyi-xu** [comment]
Hi, I have a clarification for question 3. Currently, we may have rows #1,2,4,5 representing the same variants, row #3 representing a different variant. If we add the feature of collapsing rows with the same variant, the default implementation will display row #1,3,4 where rows #1, 4 are identical. Do we want this default implementation? Or do we want to avoid displaying row #4? 

For example, this screenshot is a result of my default implementation. After collapsing rows that represent the same variant, you can see that there are duplicates in the last 4 rows. 


![Screen Shot 2022-02-11 at 12 44 27 PM](https://user-images.githubusercontent.com/56279639/153644927-56132c0c-6476-49f5-8b82-aee38cc54ce9.png)

**Comment by jennyziyi-xu** [comment]
As Hannah and I discussed, in order to better implement subtask 3, a few steps need to be done beforehand:

- [x] Add a column "Unique ID" such that the same variants are given the same unique ID. This column will be always hidden. 
- [x] Make the default sorting state by "Unique ID" only.
