### ISSUE TITLE
Research: Alternatives to query large genes. 

### ISSUE THREAD

**Issue by jennyziyi-xu** [ccmbioinfo/osmp#206]
For VEP annotations, querying genes that are larger than 0.6 million base pairs would return 500 Internal server errors. Since the searched gene can be of any size, increasing Node.js heap size would not be a feasible solution as there's no upper limit as to how large is the gene. 

One option is to chunk the gene up into shorter base pair sequences and query the sequences sequentially (Hannah). Once the result is returned for the first sequence of base pairs, send the payload to the frontend. The same applies for the second sequence of base pairs, and so on. 

- [ ] Research alternative solutions

**Comment by hannahle** [comment]
Things that I have tried that didn't work: 
- Cluster variants into groups with start and end of less than 0.3 Mbp, and send parallel queries. The server ends up crashing. 
- CSI index should allow you to query large regions, but it still crashes the server. 

We should think about some sort of algorithm that would chunk the genome regions in such a way that it would allow us to send queries of these small regions.

**Comment by jennyziyi-xu** [comment]
> Cluster variants into groups with start and end of less than 0.3 Mbp, and send parallel queries. The server ends up crashing.

Instead of sending parallel queries, we could send them sequentially. Would that be a feasible option to try?

**Comment by hannahle** [comment]
> > Cluster variants into groups with start and end of less than 0.3 Mbp, and send parallel queries. The server ends up crashing.
> 
> Instead of sending parallel queries, we could send them sequentially. Would that be a feasible option to try?

Yes, totally! That would be something we should try.

**Comment by jennyziyi-xu** [comment]
I think the common practice is to use JSON streaming which reads the JSON response over time. We can picture it as chunking up the JSON response. 
One JSON streaming package I found so far is [stream-json](https://www.npmjs.com/package/stream-json).

**Comment by jennyziyi-xu** [comment]
Now, when the size of the gene is very large (eg: DMD), `ssmp-server` crashes [here](https://github.com/ccmbioinfo/osmp/blob/1b7bb96dd3b8725cfe0b2bc03df9e42647b9740c/server/src/resolvers/getVariantsResolver/utils/fetchCaddAnnotations.ts#L42) in `fetchCaddAnnotations.ts` because the array `lines` will eventually run out of memory. 

I don't think that JSON streaming or any other method of returning the response from VEP annotations in chunks will be a feasible solution. 
Reason: we perform VEP annotations by matching the variant's key with annotationResponse's key: [annotateCadd.ts](https://github.com/ccmbioinfo/osmp/blob/1b7bb96dd3b8725cfe0b2bc03df9e42647b9740c/server/src/resolvers/getVariantsResolver/utils/annotateCadd.ts#L16). Thus, all VEP annotations must be available for this matching process to be successful.
