### ISSUE TITLE
DevOps: Promote OSMP to production instance 

### ISSUE THREAD

**Issue by jennyziyi-xu** [ccmbioinfo/osmp#270]
- Design the production deployment of the OSMP project. 
- Evaluate the next steps and internal and external requirements for the deployment. 
- Consult CHEO and PhenoTips for the next steps.

**Comment by jennyziyi-xu** [comment]
https://github.com/compose-spec/compose-spec/blob/master/spec.md#cpu_count you can resource cap containers (Kevin Lu)

**Comment by jennyziyi-xu** [comment]
- Phenotips production instance limits the amount of variant returned to be 1000. Searching for gene "LAMA3" returns 133 variants (83 unique variants in 133 individuals) and it's taking 20 MB in the `server` container. Thus, even if we get 1000 variants from Phenotips, it's going to take less than 0.5 GB. 
- CADD annotations alone take 5GB for a gene of size 0.6 Mbps. For example, the gene "NFIA" has 0.597535 Mbps. The largest gene "CNTNAP2" has 2.3 Mbps and we expect it to take 20GB. 
- Memory usage by gnomAD annotations is negligible because MongoDB query only returns matching data. 
- When multiple users query at the same time, the memory usage depends on the sum total of memory used by all the queries.

**Comment by jennyziyi-xu** [comment]
![Screen Shot 2022-07-12 at 11 48 17 AM](https://user-images.githubusercontent.com/56279639/178533973-833a492b-4a74-4454-9b3a-4f7d504e5f57.png)
MongoDB profile when only storing gnomAD GRCh37 exome annotation file in MongoDB.

**Comment by themisteryang** [comment]
> ![Screen Shot 2022-07-12 at 11 48 17 AM](https://user-images.githubusercontent.com/56279639/178533973-833a492b-4a74-4454-9b3a-4f7d504e5f57.png) MongoDB profile when only storing gnomAD GRCh37 exome annotation file in MongoDB.

<img width="1168" alt="Screen Shot 2022-07-12 at 11 53 48 AM" src="https://user-images.githubusercontent.com/39896715/178536519-80b57af2-901c-42b6-a024-f7adabbcb549.png">

This is with the gnomAD GRCh37 genome annotations as well.

**Comment by jennyziyi-xu** [comment]
It would be better if the index size fits in the memory. Although it is fine otherwise, having a large index size that exceeds the memory by a lot might result in a lot of page faults thus hindering the performance. We can also look into "prefix Index Compression". I am not sure if "prefix Index Compression" is performed by default. 
https://medium.com/swlh/mongodb-indexes-deep-dive-understanding-indexes-9bcec6ed7aa6

Understanding storage size vs index size in MongoDB: https://www.mongodb.com/docs/manual/reference/command/collStats/

**Comment by jennyziyi-xu** [comment]
Secrets added in OSMP_PROD: 

- REACT_SOURCE_LIST
- MC_HOST
- MINIO_BUCKET

Secrets to be added:
React:

- [x] REACT_APP_GRAPHQL_URL (pending on domain name)
- [ ] REACT_APP_KEYCLOAK_AUTH_URL
- [ ] REACT_APP_KEYCLOAK_REALM
- [ ] REACT_APP_KEYCLOAK_CLIENT_ID

Server and Mongo:

- [ ] G4RD_AUTH_METHOD
- [ ] G4RD_PASSWORD
- [ ] G4RD_URL
- [ ] G4RD_USERNAME
- [ ] G4RD_REALM
- [ ] G4RD_GRANT_TYPE
- [ ] G4RD_TOKEN_URL
- [ ] G4RD_CLIENT_ID
- [ ] G4RD_AUTH0_BASE_URL
- [ ] MONGO_CONNECTION_STRING (pending on account creation)

Keycloak 

- [ ] KEYCLOAK_DB_ADDR
- [ ] KEYCLOAK_DB
- [ ] KEYCLOAK_DB_USER
- [ ] KEYCLOAK_DB_PASSWORD
- [ ] KEYCLOAK_REALM
- [ ] KEYCLOAK_AUTH_URL
- [ ] KEYCLOAK_CLIENT_ID

SSH Config 

- [x] DEPLOY_PRIVATE_KEY 
- [x] DEPLOY_HOST_KEY
- [x] DEPLOY_SSH_HOST
