### ISSUE TITLE
React: frontend audit 

### ISSUE THREAD

**Issue by jennyziyi-xu** [ccmbioinfo/osmp#275]
- Review the core UI functionalities of the web portal. Make sure that the UI works as expected. 
- Catch and fix frontend bugs.

**Comment by jennyziyi-xu** [comment]
I found a few areas of improvement: 

- [x] When we customize the order of the columns, the line splitter goes out of sync: 
![Screen Shot 2022-06-17 at 10 24 31 AM](https://user-images.githubusercontent.com/56279639/174317607-4b199e81-ee13-4b4a-9f4e-7009a306df9f.png)

- [ ] We can move "Clear all filters" button near "Active Filters" since they are directly associated with each other.

**Comment by themisteryang** [comment]
#277 fixes two outstanding bugs in the Button component and the numeric filter.

**Comment by jennyziyi-xu** [comment]
Here is the proposed UI change to display "Clear all filters" button and "Active Filters" closer to each other: 
![Screen Shot 2022-06-17 at 11 39 53 AM](https://user-images.githubusercontent.com/56279639/174338538-08cabc30-b67c-4760-a49c-9817d48cf828.png)

**Comment by themisteryang** [comment]
> I found a few areas of improvement:
> 
> * [x]  When we customize the order of the columns, the line splitter goes out of sync:
>   ![Screen Shot 2022-06-17 at 10 24 31 AM](https://user-images.githubusercontent.com/56279639/174317607-4b199e81-ee13-4b4a-9f4e-7009a306df9f.png)
> * [ ]  We can move "Clear all filters" button near "Active Filters" since they are directly associated with each other.

#279 fixes the misalignment/out of sync bug with the column group divider.

**Comment by jennyziyi-xu** [comment]
> > I found a few areas of improvement:
> > 
> > * [x]   When we customize the order of the columns, the line splitter goes out of sync:
> >   ![Screen Shot 2022-06-17 at 10 24 31 AM](https://user-images.githubusercontent.com/56279639/174317607-4b199e81-ee13-4b4a-9f4e-7009a306df9f.png)
> > * [ ]   We can move "Clear all filters" button near "Active Filters" since they are directly associated with each other.
> 
> #279 fixes the misalignment/out of sync bug with the column group divider.

Ok, thank you!
