### ISSUE TITLE
Node: Use refresh tokens when cached access token fails

### ISSUE THREAD

**Issue by frewmack** [ccmbioinfo/osmp#298]
Currently for the G4RD endpoints, if the cached access token expires or otherwise fails, the server requests a brand new token using its saved credentials. The token endpoint usually responds with a refresh token in addition to an access token. 

The server should attempt to gain a new access token first using the refresh token if the cached token expires or otherwise fails. If the refresh token has also expired, then the server should request a new token as before.

**Comment by themisteryang** [comment]
Closing this issue as the `refresh_token` grant type isn't enabled for our application in Auth0.
* We are able to get a refresh token by including the `offline_access` scope when making a `POST` request to the `oauth/token` endpoint.
* However, setting `grant_type` to `refresh_token` and providing the acquired refresh token when making a `POST` request to the `oauth/token` endpoint (to exchange the refresh token for a new ID token) results in a `403` error:
```
{
    "error": "unauthorized_client",
    "error_description": "Grant type 'refresh_token' not allowed for the client.",
    "error_uri": "https://auth0.com/docs/clients/client-grant-types"
}
```
