### ISSUE TITLE
React: Gene names that are only in one assembly don't come up in gene name autocomplete. 

### ISSUE THREAD

**Issue by jennyziyi-xu** [ccmbioinfo/osmp#320]
Please refer to the conversation thread started on August 23rd on Slack in the channel "osmp-dev". The exact fixes and features to implement are still in discussion with CHEO and Madeline. 

In summary, the issue is that when OSMP makes a gene query to [mygene.info](http://mygene.info/), only hits that are in both assembly GRCh37 and GRCh38 are displayed for the users of OSMP, independent of the assembly specified by the user. For the gene CIROP for example, it only has one hit and that hit is only in GRCh38 assembly, so that's why it is not shown on OSMP.

**Comment by frewmack** [comment]
This is no longer an issue. Tested now with CIROP, and the result appears if GRCh38 is selected but not when GRCh37 is selected. This seems to be the intended behaviour.
