### ISSUE TITLE
Automatically deploy frontend

### ISSUE THREAD

**Issue by kevinlul** [ccmbioinfo/osmp#64]
A GitHub Actions workflow should perform the CRA build process and upload the resulting static site artifacts. We can adopt the process from Stager with an nginx reverse proxy for a MinIO bucket, again in the CHEO-RI tenancy.

- [x] Create bucket ssmp-site-dev.minio.genomics4rd.ca and corresponding access key pair for CD uploads
- [x] Add Actions workflow step to build the frontend and upload artifacts, with the same script from Stager but different credentials
- [x] Deploy reverse proxy at ssmp.ccmdev.ca in the CHEO-RI tenancy

**Comment by kevinlul** [comment]
Regarding this [deploy script](https://github.com/ccmbioinfo/stager/blob/master/react/deploy.sh), what option do you prefer?
- put a copy in this repo
- download the script from the other repo during a workflow run
- create a custom action that bundles the script

**Comment by hannahle** [comment]
> Regarding this [deploy script](https://github.com/ccmbioinfo/stager/blob/master/react/deploy.sh), what option do you prefer?
> 
> * put a copy in this repo
> * download the script from the other repo during a workflow run
> * create a custom action that bundles the script

Right now I have a copy in this repo, but the last option seems the cleanest.
