### ISSUE TITLE
Typescript: Stop duplicating types

### ISSUE THREAD

**Issue by cklamann** [ccmbioinfo/osmp#90]
We have many duplicated types in the react and node applications. It would be convenient and less confusing if they were consolidated. Our solution must ensure that the applications can continue to resolve the types independently of each other (e.g., within their respective containers, during builds).

**Comment by hannahle** [comment]
Temporarily closing this since the potential solution (using `create-react-app rewired` is not a sustainable workaround due to lack of maintenance. See more here: https://github.com/facebook/create-react-app/issues/8785)
