### ISSUE TITLE
React: handle column overflow

### ISSUE THREAD

**Issue by cklamann** [ccmbioinfo/osmp#95]
It's possible that we will get very large strings in some fields (esp alt/ref for large indels). We should accommodate these by styling the column fields with `overflow: ellipsis` and providing a popover for users to view the full result.

**Comment by hannahle** [comment]
Gene with long alt/ref overflow: MALRD1
Longest ref in Stager DB: NOC4

**Comment by cklamann** [comment]
what happens when the ref is so big it overflows the overflow display? :smiley: 
![image](https://user-images.githubusercontent.com/12862284/139503536-8f9f4824-9358-4852-9cb3-952ac7cad93f.png)
